CREATE TABLE IF NOT EXISTS ctr.country (
  cod VARCHAR(3) PRIMARY KEY,
  cod_alpha2 VARCHAR(2) NOT NULL,
  cod_numeric INTEGER NOT NULL,
  "name" VARCHAR(30) NOT NULL,
  name_iso VARCHAR(120) NOT NULL,
  name_official VARCHAR(120) NOT NULL,
  descr VARCHAR(240) DEFAULT '',
  active BOOLEAN DEFAULT TRUE
);

INSERT INTO ctr.country (cod, cod_alpha2, cod_numeric, "name", name_iso, name_official, descr)
VALUES
  ('ABW','AW',533,'Aruba','Aruba','Aruba','NLD'),
  ('AFG','AF',4,'Afghanistan','Afghanistan','The Islamic Republic of Afghanistan',''),
  ('AGO','AO',24,'Angola','Angola','The Republic of Angola',''),
  ('AIA','AI',660,'Anguilla','Anguilla','Anguilla','GBR'),
  ('ALA','AX',248,'Aland Islands','Aland Islands','Åland','FIN'),
  ('ALB','AL',8,'Albania','Albania','The Republic of Albania',''),
  ('AND','AD',20,'Andorra','Andorra','The Principality of Andorra',''),
  ('ARE','AE',784,'United Arab Emirates','United Arab Emirates','The United Arab Emirates',''),
  ('ARG','AR',32,'Argentina','Argentina','The Argentine Republic',''),
  ('ARM','AM',51,'Armenia','Armenia','The Republic of Armenia',''),
  ('ASM','AS',16,'American Samoa','American Samoa','The Territory of American Samoa','USA'),
  ('ATA','AQ',10,'Antarctica','Antarctica','All land and ice shelves south of the 60th parallel south','Antartica Treaty'),
  ('ATF','TF',260,'French Southern Territories','French Southern Territories','The French Southern and Antarctic Lands','FRA'),
  ('ATG','AG',28,'Antigua and Barbuda','Antigua and Barbuda','Antigua and Barbuda',''),
  ('AUS','AU',36,'Australia','Australia','The Commonwealth of Australia',''),
  ('AUT','AT',40,'Austria','Austria','The Republic of Austria',''),
  ('AZE','AZ',31,'Azerbaijan','ß','The Republic of Azerbaijan',''),
  ('BDI','BI',108,'Burundi','Burundi','The Republic of Burundi',''),
  ('BEL','BE',56,'Belgium','Belgium','The Kingdom of Belgium',''),
  ('BEN','BJ',204,'Benin','Benin','The Republic of Benin',''),
  ('BES','BQ',535,'Bonaire and others','Bonaire, Sint Eustatius and Saba','Bonaire, Sint Eustatius and Saba','NLD'),
  ('BFA','BF',854,'Burkina Faso','Burkina Faso','Burkina Faso',''),
  ('BGD','BD',50,'Bangladesh','Bangladesh','The Peoples Republic of Bangladesh',''),
  ('BGR','BG',100,'Bulgaria','Bulgaria','The Republic of Bulgaria',''),
  ('BHR','BH',48,'Bahrain','Bahrain','The Kingdom of Bahrain',''),
  ('BHS','BS',44,'Bahamas','Bahamas','The Commonwealth of The Bahamas',''),
  ('BIH','BA',70,'Bosnia and Herzegovina','Bosnia and Herzegovina','Bosnia and Herzegovina',''),
  ('BLM','BL',652,'Saint Barthelemy','Saint Barthelemy','The Collectivity of Saint-Barthélemy','FRA'),
  ('BLR','BY',112,'Belarus','Belarus','The Republic of Belarus',''),
  ('BLZ','BZ',84,'Belize','Belize','Belize',''),
  ('BMU','BM',60,'Bermuda','Bermuda','Bermuda','GBR'),
  ('BOL','BO',68,'Bolivia','Bolivia','The Plurinational State of Bolivia',''),
  ('BRA','BR',76,'Brazil','Brazil','The Federative Republic of Brazil',''),
  ('BRB','BB',52,'Barbados','Barbados','Barbados',''),
  ('BRN','BN',96,'Brunei Darussalam','Brunei Darussalam','The Nation of Brunei, the Abode of Peace',''),
  ('BTN','BT',64,'Bhutan','Bhutan','The Kingdom of Bhutan',''),
  ('BVT','BV',74,'Bouvet Island','Bouvet Island','Bouvet Island','NOR'),
  ('BWA','BW',72,'Botswana','Botswana','The Republic of Botswana',''),
  ('CAF','CF',140,'Central African Republic','Central African Republic','The Central African Republic',''),
  ('CAN','CA',124,'Canada','Canada','Canada',''),
  ('CCK','CC',166,'Cocos (Keeling) Islands','Cocos (Keeling) Islands','The Territory of Cocos (Keeling) Islands','AUS'),
  ('CHE','CH',756,'Switzerland','Switzerland','The Swiss Confederation',''),
  ('CHL','CL',152,'Chile','Chile','The Republic of Chile',''),
  ('CHN','CN',156,'China','China','The Peoples Republic of China',''),
  ('CIV','CI',384,'Ivory Coast','Ivory Coast','The Republic of Côte dIvoire',''),
  ('CMR','CM',120,'Cameroon','Cameroon','The Republic of Cameroon',''),
  ('COD','CD',180,'Congo (Democratic Republic)','Congo (Democratic Republic of the)','The Democratic Republic of the Congo',''),
  ('COG','CG',178,'Congo','Congo','The Republic of the Congo',''),
  ('COK','CK',184,'Cook Islands','Cook Islands','The Cook Islands','NZL'),
  ('COL','CO',170,'Colombia','Colombia','The Republic of Colombia',''),
  ('COM','KM',174,'Comoros','Comoros','The Union of the Comoros',''),
  ('CPV','CV',132,'Cabo Verde','Cabo Verde','The Republic of Cabo Verde',''),
  ('CRI','CR',188,'Costa Rica','Costa Rica','The Republic of Costa Rica',''),
  ('CUB','CU',192,'Cuba','Cuba','The Republic of Cuba',''),
  ('CUW','CW',531,'Curaçao','Curaçao','The Country of Curaçao','NLD'),
  ('CXR','CX',162,'Saint Helena and others','Saint Helena, Ascension and Tristan da Cunha','The Territory of Christmas Island','AUS'),
  ('CYM','KY',136,'Cayman Islands','Cayman Islands','The Cayman Islands','GBR'),
  ('CYP','CY',196,'Cyprus','Cyprus','The Republic of Cyprus',''),
  ('CZE','CZ',203,'Czechia','Czechia','The Czech Republic',''),
  ('DEU','DE',276,'Germany','Germany','The Federal Republic of Germany',''),
  ('DJI','DJ',262,'Djibouti','Djibouti','The Republic of Djibouti',''),
  ('DMA','DM',212,'Dominica','Dominica','The Commonwealth of Dominica',''),
  ('DNK','DK',208,'Denmark','Denmark','The Kingdom of Denmark',''),
  ('DOM','DO',214,'Dominican Republic','Dominican Republic','The Dominican Republic',''),
  ('DZA','DZ',12,'Algeria','Algeria','The Peoples Democratic Republic of Algeria',''),
  ('ECU','EC',218,'Ecuador','Ecuador','The Republic of Ecuador',''),
  ('EGY','EG',818,'Egypt','Egypt','The Arab Republic of Egypt',''),
  ('ERI','ER',232,'Eritrea','Eritrea','The State of Eritrea',''),
  ('ESH','EH',732,'Western Sahara','Western Sahara','The Sahrawi Arab Democratic Republic','Disputed'),
  ('ESP','ES',724,'Spain','Spain','The Kingdom of Spain',''),
  ('EST','EE',233,'Estonia','Estonia','The Republic of Estonia',''),
  ('ETH','ET',231,'Ethiopia','Ethiopia','The Federal Democratic Republic of Ethiopia',''),
  ('FIN','FI',246,'Finland','Finland','The Republic of Finland',''),
  ('FJI','FJ',242,'Fiji','Fiji','The Republic of Fiji',''),
  ('FLK','FK',238,'Falkland Islands','Falkland Islands','The Falkland Islands','GBR'),
  ('FRA','FR',250,'France','France','The French Republic',''),
  ('FRO','FO',234,'Faroe Islands','Faroe Islands','The Faroe Islands','DNK'),
  ('FSM','FM',583,'Micronesia','Micronesia','The Federated States of Micronesia',''),
  ('GAB','GA',266,'Gabon','Gabon','The Gabonese Republic',''),
  ('GBR','GB',826,'United Kingdom','United Kingdom','The United Kingdom of Great Britain and Northern Ireland',''),
  ('GEO','GE',268,'Georgia','Georgia','Georgia',''),
  ('GGY','GG',831,'Guernsey','Guernsey','The Bailiwick of Guernsey',''),
  ('GHA','GH',288,'Ghana','Ghana','The Republic of Ghana',''),
  ('GIB','GI',292,'Gibraltar','Gibraltar','Gibraltar','GBR'),
  ('GIN','GN',324,'Guinea','Guinea','The Republic of Guinea',''),
  ('GLP','GP',312,'Guadeloupe','Guadeloupe','Guadeloupe','FRA'),
  ('GMB','GM',270,'Gambia','Gambia','The Republic of The Gambia',''),
  ('GNB','GW',624,'Guinea-Bissau','Guinea-Bissau','The Republic of Guinea-Bissau',''),
  ('GNQ','GQ',226,'Equatorial Guinea','Equatorial Guinea','The Republic of Equatorial Guinea',''),
  ('GRC','GR',300,'Greece','Greece','The Hellenic Republic',''),
  ('GRD','GD',308,'Grenada','Grenada','Grenada',''),
  ('GRL','GL',304,'Greenland','Greenland','Kalaallit Nunaat','DNK'),
  ('GTM','GT',320,'Guatemala','Guatemala','The Republic of Guatemala',''),
  ('GUF','GF',254,'French Guiana','French Guiana','Guyane','FRA'),
  ('GUM','GU',316,'Guam','Guam','The Territory of Guam','USA'),
  ('GUY','GY',328,'Guyana','Guyana','The Co-operative Republic of Guyana',''),
  ('HKG','HK',344,'Hong Kong','Hong Kong','The Hong Kong Special Administrative Region of China','CHN'),
  ('HMD','HM',334,'Heard Island and others','Heard Island and McDonald Islands','The Territory of Heard Island and McDonald Islands','AUS'),
  ('HND','HN',340,'Honduras','Honduras','The Republic of Honduras',''),
  ('HRV','HR',191,'Croatia','Croatia','The Republic of Croatia',''),
  ('HTI','HT',332,'Haiti','Haiti','The Republic of Haiti',''),
  ('HUN','HU',348,'Hungary','Hungary','Hungary',''),
  ('IDN','ID',360,'Indonesia','Indonesia','The Republic of Indonesia',''),
  ('IMN','IM',833,'Isle of Man','Isle of Man','The Isle of Man',''),
  ('IND','IN',356,'India','India','The Republic of India',''),
  ('IOT','IO',86,'British Indian Ocean Territory','British Indian Ocean Territory','The British Indian Ocean Territory','GBR'),
  ('IRL','IE',372,'Ireland','Ireland','Ireland',''),
  ('IRN','IR',364,'Iran','Iran','The Islamic Republic of Iran',''),
  ('IRQ','IQ',368,'Iraq','Iraq','The Republic of Iraq',''),
  ('ISL','IS',352,'Iceland','Iceland','Iceland',''),
  ('ISR','IL',376,'Israel','Israel','The State of Israel',''),
  ('ITA','IT',380,'Italy','Italy','The Italian Republic',''),
  ('JAM','JM',388,'Jamaica','Jamaica','Jamaica',''),
  ('JEY','JE',832,'Jersey','Jersey','The Bailiwick of Jersey',''),
  ('JOR','JO',400,'Jordan','Jordan','The Hashemite Kingdom of Jordan',''),
  ('JPN','JP',392,'Japan','Japan','Japan',''),
  ('KAZ','KZ',398,'Kazakhstan','Kazakhstan','The Republic of Kazakhstan',''),
  ('KEN','KE',404,'Kenya','Kenya','The Republic of Kenya',''),
  ('KGZ','KG',417,'Kyrgyzstan','Kyrgyzstan','The Kyrgyz Republic',''),
  ('KHM','KH',116,'Cambodia','Cambodia','The Kingdom of Cambodia',''),
  ('KIR','KI',296,'Kiribati','Kiribati','The Republic of Kiribati',''),
  ('KNA','KN',659,'Saint Kitts and Nevis','Saint Kitts and Nevis','Saint Kitts and Nevis',''),
  ('KOR','KR',410,'Korea','Korea','The Republic of Korea',''),
  ('KWT','KW',414,'Kuwait','Kuwait','The State of Kuwait',''),
  ('LAO','LA',418,'Lao','Lao','The Lao Peoples Democratic Republic',''),
  ('LBN','LB',422,'Lebanon','Lebanon','The Lebanese Republic',''),
  ('LBR','LR',430,'Liberia','Liberia','The Republic of Liberia',''),
  ('LBY','LY',434,'Libya','Libya','The State of Libya',''),
  ('LCA','LC',662,'Saint Lucia','Saint Lucia','Saint Lucia',''),
  ('LIE','LI',438,'Liechtenstein','Liechtenstein','The Principality of Liechtenstein',''),
  ('LKA','LK',144,'Sri Lanka','Sri Lanka','The Democratic Socialist Republic of Sri Lanka',''),
  ('LSO','LS',426,'Lesotho','Lesotho','The Kingdom of Lesotho',''),
  ('LTU','LT',440,'Lithuania','Lithuania','The Republic of Lithuania',''),
  ('LUX','LU',442,'Luxembourg','Luxembourg','The Grand Duchy of Luxembourg',''),
  ('LVA','LV',428,'Latvia','Latvia','The Republic of Latvia',''),
  ('MAC','MO',446,'Macao','Macao','The Macao Special Administrative Region of China','CHN'),
  ('MAF','MF',663,'Saint Martin (French part)','Saint Martin (French part)','The Collectivity of Saint-Martin','FRA'),
  ('MAR','MA',504,'Morocco','Morocco','The Kingdom of Morocco',''),
  ('MCO','MC',492,'Monaco','Monaco','The Principality of Monaco',''),
  ('MDA','MD',498,'Moldova','Moldova','The Republic of Moldova',''),
  ('MDG','MG',450,'Madagascar','Madagascar','The Republic of Madagascar',''),
  ('MDV','MV',462,'Maldives','Maldives','The Republic of Maldives',''),
  ('MEX','MX',484,'Mexico','Mexico','The United Mexican States',''),
  ('MHL','MH',584,'Marshall Islands','Marshall Islands','The Republic of the Marshall Islands',''),
  ('MKD','MK',807,'North Macedonia','North Macedonia','The Republic of North Macedonia[12]',''),
  ('MLI','ML',466,'Mali','Mali','The Republic of Mali',''),
  ('MLT','MT',470,'Malta','Malta','The Republic of Malta',''),
  ('MMR','MM',104,'Myanmar','Myanmar','The Republic of the Union of Myanmar',''),
  ('MNE','ME',499,'Montenegro','Montenegro','Montenegro',''),
  ('MNG','MN',496,'Mongolia','Mongolia','Mongolia',''),
  ('MNP','MP',580,'Northern Mariana Islands','Northern Mariana Islands','The Commonwealth of the Northern Mariana Islands','USA'),
  ('MOZ','MZ',508,'Mozambique','Mozambique','The Republic of Mozambique',''),
  ('MRT','MR',478,'Mauritania','Mauritania','The Islamic Republic of Mauritania',''),
  ('MSR','MS',500,'Montserrat','Montserrat','Montserrat','GBR'),
  ('MTQ','MQ',474,'Martinique','Martinique','Martinique','FRA'),
  ('MUS','MU',480,'Mauritius','Mauritius','The Republic of Mauritius',''),
  ('MWI','MW',454,'Malawi','Malawi','The Republic of Malawi',''),
  ('MYS','MY',458,'Malaysia','Malaysia','Malaysia',''),
  ('MYT','YT',175,'Mayotte','Mayotte','The Department of Mayotte','FRA'),
  ('NAM','NA',516,'Namibia','Namibia','The Republic of Namibia',''),
  ('NCL','NC',540,'New Caledonia','New Caledonia','New Caledonia','FRA'),
  ('NER','NE',562,'Niger','Niger','The Republic of the Niger',''),
  ('NFK','NF',574,'Norfolk Island','Norfolk Island','The Territory of Norfolk Island','AUS'),
  ('NGA','NG',566,'Nigeria','Nigeria','The Federal Republic of Nigeria',''),
  ('NIC','NI',558,'Nicaragua','Nicaragua','The Republic of Nicaragua',''),
  ('NIU','NU',570,'Niue','Niue','Niue','NZL'),
  ('NLD','NL',528,'Netherlands','Netherlands','The Kingdom of the Netherlands',''),
  ('NOR','NO',578,'Norway','Norway','The Kingdom of Norway',''),
  ('NPL','NP',524,'Nepal','Nepal','The Federal Democratic Republic of Nepal',''),
  ('NRU','NR',520,'Nauru','Nauru','The Republic of Nauru',''),
  ('NZL','NZ',554,'New Zealand','New Zealand','New Zealand',''),
  ('OMN','OM',512,'Oman','Oman','The Sultanate of Oman',''),
  ('PAK','PK',586,'Pakistan','Pakistan','The Islamic Republic of Pakistan',''),
  ('PAN','PA',591,'Panama','Panama','The Republic of Panamá',''),
  ('PCN','PN',612,'Pitcairn','Pitcairn','The Pitcairn, Henderson, Ducie and Oeno Islands','GBR'),
  ('PER','PE',604,'Peru','Peru','The Republic of Perú',''),
  ('PHL','PH',608,'Philippines','Philippines','The Republic of the Philippines',''),
  ('PLW','PW',585,'Palau','Palau','The Republic of Palau',''),
  ('PNG','PG',598,'Papua New Guinea','Papua New Guinea','The Independent State of Papua New Guinea',''),
  ('POL','PL',616,'Poland','Poland','The Republic of Poland',''),
  ('PRI','PR',630,'Puerto Rico','Puerto Rico','The Commonwealth of Puerto Rico','USA'),
  ('PRK','KP',408,'North Korea','North Korea','The Democratic Peoples Republic of Korea',''),
  ('PRT','PT',620,'Portugal','Portugal','The Portuguese Republic',''),
  ('PRY','PY',600,'Paraguay','Paraguay','The Republic of Paraguay',''),
  ('PSE','PS',275,'Palestine','Palestine','The State of Palestine',''),
  ('PYF','PF',258,'French Polynesia','French Polynesia','French Polynesia','FRA'),
  ('QAT','QA',634,'Qatar','Qatar','The State of Qatar',''),
  ('REU','RE',638,'Réunion','Réunion','Réunion','FRA'),
  ('ROU','RO',642,'Romania','Romania','Romania',''),
  ('RUS','RU',643,'Russia','Russia','The Russian Federation',''),
  ('RWA','RW',646,'Rwanda','Rwanda','The Republic of Rwanda',''),
  ('SAU','SA',682,'Saudi Arabia','Saudi Arabia','The Kingdom of Saudi Arabia',''),
  ('SDN','SD',729,'Sudan','Sudan','The Republic of the Sudan',''),
  ('SEN','SN',686,'Senegal','Senegal','The Republic of Senegal',''),
  ('SGP','SG',702,'Singapore','Singapore','The Republic of Singapore',''),
  ('SGS','GS',239,'South Georgia and others','South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands','GBR'),
  ('SHN','SH',654,'Saint Helena and others','Saint Helena, Ascension and Tristan da Cunha','Saint Helena, Ascension and Tristan da Cunha','GBR'),
  ('SJM','SJ',744,'Svalbard and Jan Mayen','Svalbard and Jan Mayen','Svalbard and Jan Mayen','NOR'),
  ('SLB','SB',90,'Solomon Islands','Solomon Islands','The Solomon Islands',''),
  ('SLE','SL',694,'Sierra Leone','Sierra Leone','The Republic of Sierra Leone',''),
  ('SLV','SV',222,'El Salvador','El Salvador','The Republic of El Salvador',''),
  ('SMR','SM',674,'San Marino','San Marino','The Republic of San Marino',''),
  ('SOM','SO',706,'Somalia','Somalia','The Federal Republic of Somalia',''),
  ('SPM','PM',666,'Saint Pierre and Miquelon','Saint Pierre and Miquelon','The Overseas Collectivity of Saint-Pierre and Miquelon','FRA'),
  ('SRB','RS',688,'Serbia','Serbia','The Republic of Serbia',''),
  ('SSD','SS',728,'South Sudan','South Sudan','The Republic of South Sudan',''),
  ('STP','ST',678,'Sao Tome and Principe','Sao Tome and Principe','The Democratic Republic of São Tomé and Príncipe',''),
  ('SUR','SR',740,'Suriname','Suriname','The Republic of Suriname',''),
  ('SVK','SK',703,'Slovakia','Slovakia','The Slovak Republic',''),
  ('SVN','SI',705,'Slovenia','Slovenia','The Republic of Slovenia',''),
  ('SWE','SE',752,'Sweden','Sweden','The Kingdom of Sweden',''),
  ('SWZ','SZ',748,'Eswatini','Eswatini','The Kingdom of Eswatini',''),
  ('SXM','SX',534,'Sint Maarten (Dutch part)','Sint Maarten (Dutch part)','Sint Maarten','NLD'),
  ('SYC','SC',690,'Seychelles','Seychelles','The Republic of Seychelles',''),
  ('SYR','SY',760,'Syria','Syria','The Syrian Arab Republic',''),
  ('TCA','TC',796,'Turks and Caicos Islands','Turks and Caicos Islands','The Turks and Caicos Islands','GBR'),
  ('TCD','TD',148,'Chad','Chad','The Republic of Chad',''),
  ('TGO','TG',768,'Togo','Togo','The Togolese Republic',''),
  ('THA','TH',764,'Thailand','Thailand','The Kingdom of Thailand',''),
  ('TJK','TJ',762,'Tajikistan','Tajikistan','The Republic of Tajikistan',''),
  ('TKL','TK',772,'Tokelau','Tokelau','Tokelau','NZL'),
  ('TKM','TM',795,'Turkmenistan','Turkmenistan','Turkmenistan',''),
  ('TLS','TL',626,'Timor-Leste','Timor-Leste','The Democratic Republic of Timor-Leste',''),
  ('TON','TO',776,'Tonga','Tonga','The Kingdom of Tonga',''),
  ('TTO','TT',780,'Trinidad and Tobago','Trinidad and Tobago','The Republic of Trinidad and Tobago',''),
  ('TUN','TN',788,'Tunisia','Tunisia','The Republic of Tunisia',''),
  ('TUR','TR',792,'Türkiye','Türkiye','The Republic of Türkiye',''),
  ('TUV','TV',798,'Tuvalu','Tuvalu','Tuvalu',''),
  ('TWN','TW',158,'Taiwan','Taiwan','The Republic of China','Disputed'),
  ('TZA','TZ',834,'Tanzania','Tanzania','The United Republic of Tanzania',''),
  ('UGA','UG',800,'Uganda','Uganda','The Republic of Uganda',''),
  ('UKR','UA',804,'Ukraine','Ukraine','Ukraine',''),
  ('UMI','UM',581,'US Minor Outlying Islands','United States Minor Outlying Islands','Baker Island and others','USA, Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island[13]'),
  ('URY','UY',858,'Uruguay','Uruguay','The Oriental Republic of Uruguay',''),
  ('USA','US',840,'United States','United States of America','The United States of America',''),
  ('UZB','UZ',860,'Uzbekistan','Uzbekistan','The Republic of Uzbekistan',''),
  ('VAT','VA',336,'Holy See','Holy See','The Holy See',''),
  ('VCT','VC',670,'Saint Vincent others','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines',''),
  ('VEN','VE',862,'Venezuela','Venezuela','The Bolivarian Republic of Venezuela',''),
  ('VGB','VG',92,'Virgin Islands (British)','Virgin Islands (British)','The Virgin Islands','GBR'),
  ('VIR','VI',850,'Virgin Islands (U.S.)','Virgin Islands (U.S.)','The Virgin Islands of the United States','USA'),
  ('VNM','VN',704,'Viet Nam','Viet Nam','The Socialist Republic of Viet Nam',''),
  ('VUT','VU',548,'Vanuatu','Vanuatu','The Republic of Vanuatu',''),
  ('WLF','WF',876,'Wallis and Futuna','Wallis and Futuna','The Territory of the Wallis and Futuna Islands','FRA'),
  ('WSM','WS',882,'Samoa','Samoa','The Independent State of Samoa',''),
  ('YEM','YE',887,'Yemen','Yemen','The Republic of Yemen',''),
  ('ZAF','ZA',710,'South Africa','South Africa','The Republic of South Africa',''),
  ('ZMB','ZM',894,'Zambia','Zambia','The Republic of Zambia',''),
  ('ZWE','ZW',716,'Zimbabwe','Zimbabwe','The Republic of Zimbabwe','');
